### ISSUE TITLE
Avatars are kinda offset

### ISSUE THREAD

**Issue by IgnusG** [emadow/mailspring-avatars#2]
The avatars icons are offset in a weird way where they overlap with the text.

![deepinscreenshot_select-area_20171108182808](https://user-images.githubusercontent.com/6438760/32563895-bd61ceb6-c4b2-11e7-8a0c-286f2438ff82.png)

I'm using the taiga theme bundled with mailspring in the two panel view.
Mailspring version 1.0.7
Latest release of this plugin

**Comment by IgnusG** [comment]
This line https://github.com/emadow/mailspring-avatars/blob/master/styles/index.less#L46 should be at least `50px` when the window gets smaller I think.

**Comment by emadow** [comment]
submit a PR and i'll merge!
